language: rust
os:
    - linux
env:
    global:
        - secure: cueMesBNDVRh0k/9lTOor+sS5JLelhquCiz0IhxxtpXTTPg5RixmZUgUKl6fmoNGHosyg6rlC3iPTndChRS4cllf46/RLZliWYMeo0Ik5lonqrilbINOc0Cco7YiG6C1te8GmY1zblGIIATOIKre0wOs3LFzStg4+UxlzJq7Zlc=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
