[package]

name = "fingertree"
version = "0.0.0"
authors = [ "Darin Morrison <darinmorrison+epsilonz@gmail.com>" ]
description = "Finger Trees in Rust"
documentation = "http://www.rust-ci.org/epsilonz/fingertree.rs/doc/fingertree/"
keywords = ["data-structures", "persistent", "sequences", "trees"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/epsilonz/fingertree.rs"

[lib]
name = "fingertree"
path = "src/lib.rs"

[dependencies.epsilonz_algebra]
git = "https://github.com/epsilonz/algebra.rs"

# [dev-dependencies.criterion]
# git = "https://github.com/japaric/criterion.rs"

# [dev-dependencies.criterion_macros]
# git = "https://github.com/japaric/criterion.rs"

[dev-dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dev-dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
